######################################################################
# Automatically generated by qmake (3.0) Fri May 11 14:04:36 2018
######################################################################

QT += testlib
TEMPLATE = app
TARGET = tests
INCLUDEPATH += .
CONFIG += c++11 link_pkgconfig
PKGCONFIG += libdwarf++

# Input
SOURCES += testcollector.cpp \
    ../src/collector.cpp \
    ../src/elfutil.cpp \
    ../src/procutil.cpp

HEADERS += \
    ../src/collector.h \
    ../src/constants.h \
    ../src/elfutil.h \
    ../src/procutil.h
