#ifndef SIMPLEPROFILER_GLOBAL_H
#define SIMPLEPROFILER_GLOBAL_H

#if defined(SIMPLEPROFILER_LIBRARY)
#  define SIMPLEPROFILERSHARED_EXPORT
#else
#  define SIMPLEPROFILERSHARED_EXPORT
#endif

#endif // SIMPLEPROFILER_GLOBAL_H
